export const chang = "change test";
export const LOGO = "../../assets/logo/logo.svg";

// Trainer Registration
export const sports = [
  "",
  "Aikido",
  "American Football",
  "Archery",
  "Australian Rules Football",
  "Auto Racing",
  "Badminton",
  "Base Jumping",
  "Baseball",
  "Basketball",
  "Beach Soccer",
  "Beach Volleyball",
  "Biathlon",
  "Billiards",
  "BMX",
  "Bobsleigh",
  "Bodybuilding",
  "Bocce",
  "Bowling",
  "Boxing",
  "Brazilian Jiu Jitsu",
  "Bull Riding",
  "Canoeing",
  "Capoeira",
  "Cheerleading",
  "Climbing",
  "Cricket",
  "CrossFit",
  "Curling",
  "Cycling",
  "Dance",
  "Darts",
  "Decathlon",
  "Disc Golf",
  "Diving",
  "Drag Racing",
  "Endurance Racing",
  "Equestrian",
  "Fencing",
  "Field Hockey",
  "Figure Skating",
  "Fishing",
  "Floorball",
  "Formula 1",
  "Freerunning",
  "Frisbee Golf",
  "Futsal",
  "Gaelic Football",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hang Gliding",
  "Heptathlon",
  "Hiking",
  "Hockey",
  "Horse Racing",
  "Ice Hockey",
  "Jiu Jitsu",
  "Judo",
  "Kabaddi",
  "Karate",
  "Kayaking",
  "Kickboxing",
  "Kitesurfing",
  "Krav Maga",
  "Kung Fu",
  "Lacrosse",
  "Luge",
  "Marathon",
  "Martial Arts",
  "Motorsport",
  "Mountain Biking",
  "Mountaineering",
  "Muay Thai",
  "Nascar",
  "Orienteering",
  "Paddle Tennis",
  "Paintball",
  "Paragliding",
  "Parkour",
  "Pentathlon",
  "Petanque",
  "Pickleball",
  "Platform Tennis",
  "Pole Vault",
  "Polo",
  "Powerlifting",
  "Racquetball",
  "Rally Racing",
  "Rock Climbing",
  "Rodeo",
  "Roller Derby",
  "Roller Skating",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sambo",
  "Savate",
  "Scuba Diving",
  "Sepak Takraw",
  "Shooting",
  "Skeleton",
  "Skiing",
  "Skydiving",
  "Snowboarding",
  "Soccer",
  "Softball",
  "Speleology",
  "Speed Skating",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Track and Field",
  "Trail Running",
  "Triathlon",
  "Ultimate Frisbee",
  "Underwater Hockey",
  "Underwater Rugby",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
  "Wushu",
];
