export const chang = "change test";

// Logo
export const LOGO = "../../assets/logo/logo.svg";

// Images
export const anonymousImage = "../../assets/img/anonymous/anonymous.jpeg";
export const heroImage = "../../assets/img/hero/hero.jpg";

// Home page Images
export const homeCategoriesOne = [
  "../../assets/img/home/home-category/1.png",
  "../../assets/img/home/home-category/2.png",
  "../../assets/img/home/home-category/3.png",
  "../../assets/img/home/home-category/4.png",
  "../../assets/img/home/home-category/5.png",
  "../../assets/img/home/home-category/6.png",
];
export const homeCategoriesTwo = [
  "../../assets/img/home/home-category/7.png",
  "../../assets/img/home/home-category/8.png",
  "../../assets/img/home/home-category/9.png",
  "../../assets/img/home/home-category/10.png",
  "../../assets/img/home/home-category/11.png",
  "../../assets/img/home/home-category/12.png",
];
export const homeCategoriesThree = [
  "../../assets/img/home/home-category/13.png",
  "../../assets/img/home/home-category/14.png",
  "../../assets/img/home/home-category/15.png",
  "../../assets/img/home/home-category/16.png",
  "../../assets/img/home/home-category/17.png",
  "../../assets/img/home/home-category/18.png",
];
export const becomeTrainer =
  "../../assets/img/home/become-trainer/becometrainer.jpg";
export const footerGif = "../../assets/img/footer/gif.gif";

// Become a trainer page
export const becomeTrainerImage = "../../assets/img/become-trainer/trainer.jpg";

// Footer
export const gitHubLink = "https://github.com/ArturAbel/TrainMate";

// Text
export const TRAINER = "trainer";
export const TRAINEE = "trainee";
export const ADMIN = "admin";

// Trainer Registration
export const sports = [
  "",
  "Aikido",
  "American Football",
  "Archery",
  "Australian Rules Football",
  "Auto Racing",
  "Badminton",
  "Base Jumping",
  "Baseball",
  "Basketball",
  "Beach Soccer",
  "Beach Volleyball",
  "Biathlon",
  "Billiards",
  "BMX",
  "Bobsleigh",
  "Bodybuilding",
  "Bocce",
  "Bowling",
  "Boxing",
  "Brazilian Jiu Jitsu",
  "Bull Riding",
  "Canoeing",
  "Capoeira",
  "Cheerleading",
  "Climbing",
  "Cricket",
  "CrossFit",
  "Curling",
  "Cycling",
  "Dance",
  "Darts",
  "Decathlon",
  "Disc Golf",
  "Diving",
  "Drag Racing",
  "Endurance Racing",
  "Equestrian",
  "Fencing",
  "Field Hockey",
  "Figure Skating",
  "Fishing",
  "Floorball",
  "Formula 1",
  "Freerunning",
  "Frisbee Golf",
  "Futsal",
  "Gaelic Football",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hang Gliding",
  "Heptathlon",
  "Hiking",
  "Hockey",
  "Horse Racing",
  "Ice Hockey",
  "Jiu Jitsu",
  "Judo",
  "Kabaddi",
  "Karate",
  "Kayaking",
  "Kickboxing",
  "Kitesurfing",
  "Krav Maga",
  "Kung Fu",
  "Lacrosse",
  "Luge",
  "Marathon",
  "Martial Arts",
  "Motorsport",
  "Mountain Biking",
  "Mountaineering",
  "Muay Thai",
  "Nascar",
  "Orienteering",
  "Paddle Tennis",
  "Paintball",
  "Paragliding",
  "Parkour",
  "Pentathlon",
  "Petanque",
  "Pickleball",
  "Platform Tennis",
  "Pole Vault",
  "Polo",
  "Powerlifting",
  "Racquetball",
  "Rally Racing",
  "Rock Climbing",
  "Rodeo",
  "Roller Derby",
  "Roller Skating",
  "Rowing",
  "Rugby",
  "Sailing",
  "Sambo",
  "Savate",
  "Scuba Diving",
  "Sepak Takraw",
  "Shooting",
  "Skeleton",
  "Skiing",
  "Skydiving",
  "Snowboarding",
  "Soccer",
  "Softball",
  "Speleology",
  "Speed Skating",
  "Squash",
  "Sumo Wrestling",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Track and Field",
  "Trail Running",
  "Triathlon",
  "Ultimate Frisbee",
  "Underwater Hockey",
  "Underwater Rugby",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Windsurfing",
  "Wrestling",
  "Wushu",
];
